#!/bin/bash
set -euo pipefail
umask 077
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
STATE=/mnt/user/appdata/hermes/operator-state; PENDING=$STATE/pending; USED=$STATE/used
BACKUPS=/mnt/user/appdata/hermes/operator-backups; STAGING=/mnt/user/appdata/hermes/data/operator-staging
AUDIT=/mnt/user/appdata/hermes/operator-audit.jsonl; TTL=600
mkdir -p "$PENDING" "$USED" "$BACKUPS"; chmod 700 "$STATE" "$PENDING" "$USED" "$BACKUPS"; install -d -m 700 -o 10000 -g 10000 "$STAGING"
deny() { echo "DENIED: $*" >&2; exit 64; }
valid_name() { [[ $1 =~ ^[A-Za-z0-9_.:-]+$ ]]; }
decode_b64() { printf '%s' "$1" | base64 -d 2>/dev/null || deny "invalid base64 argument"; }
audit() {
  local action=$1 target=$2 result=$3 incident=${4:-unknown} diagnosis=${5:-not-provided} approved=${6:-not-provided} validation=${7:-pending} rollback=${8:-no}
  jq -cn --arg ts "$(date -u +%FT%TZ)" --arg user telegram/remco --arg incident "$incident" --arg diagnosis "$diagnosis" --arg action "$action" --arg target "$target" --arg approved_action "${SSH_ORIGINAL_COMMAND:-}" --arg approval_timestamp "$approved" --arg result "$result" --arg validation "$validation" --arg rollback "$rollback" '{timestamp:$ts,user_request:$user,incident_id:$incident,diagnosis_summary:$diagnosis,action_type:$action,target:$target,approved_action:$approved_action,approval_timestamp:$approval_timestamp,execution_result:$result,validation_result:$validation,rollback_performed:$rollback}' >> "$AUDIT"; chmod 600 "$AUDIT"
}
normal_path() {
  local p=$1 parent resolved; [[ $p == /* && $p != *$'\n'* ]] || deny "invalid absolute path"; parent=$(dirname -- "$p"); resolved=$(realpath -m -- "$parent")/$(basename -- "$p")
  case "$resolved" in /mnt/user/appdata/*|/mnt/vm_storage/config/*) printf '%s' "$resolved";; *) deny "path outside normal write roots";; esac
}
compose_dir() { local d; d=$(normal_path "$1"); [[ -d $d && ( -f $d/docker-compose.yml || -f $d/compose.yml ) ]] || deny "invalid compose directory"; printf '%s' "$d"; }
vm_name() { local n=$1; [[ -n $n && ${#n} -le 128 && $n != *$'\n'* ]] || deny "invalid VM name"; virsh dominfo "$n" >/dev/null 2>&1 || deny "unknown VM"; printf '%s' "$n"; }
service_script() { case "$1" in docker|libvirt|nginx|php-fpm|samba|nfsd|smartd|unraid-api) ;; *) deny "service not allowlisted";; esac; local s=/etc/rc.d/rc.$1; [[ -r $s ]] || deny "service script unavailable"; printf '%s' "$s"; }
backup_file() { local p=$1 stamp dest; [[ -f $p && ! -L $p ]] || deny "source is not a regular file"; stamp=$(date -u +%Y%m%d-%H%M%S); dest="$BACKUPS${p}.bak-$stamp"; mkdir -p "$(dirname "$dest")"; cp -a -- "$p" "$dest"; printf '%s' "$dest"; }
validate_config() {
  local p=$1 kind=${2:-auto}; case "$kind" in
    compose) docker compose -f "$p" config -q;; json) jq -e . "$p" >/dev/null;; xml) php -r '$d=new DOMDocument(); if(!@$d->load($argv[1])) exit(1);' "$p";; shell) bash -n "$p";;
    auto) case "$p" in *.json) jq -e . "$p" >/dev/null;; *.xml) php -r '$d=new DOMDocument(); if(!@$d->load($argv[1])) exit(1);' "$p";; *.sh) bash -n "$p";; *compose*.yml|*compose*.yaml) docker compose -f "$p" config -q;; *) return 0;; esac;;
    none) return 0;; *) deny "unknown validator";; esac
}
metadata() { INCIDENT=${1:-unknown}; APPROVED=${2:-not-provided}; [[ $INCIDENT =~ ^[A-Za-z0-9_.:-]{1,128}$ ]] || deny "invalid incident id"; [[ $APPROVED =~ ^[0-9TZ:+.-]{1,40}$|^not-provided$ ]] || deny "invalid approval timestamp"; }
read -r -a argv <<< "${SSH_ORIGINAL_COMMAND:-}"; action=${argv[0]:-}
case "$action" in
  docker-start|docker-restart|docker-stop)
    name=${argv[1]:-}; valid_name "$name" || deny "invalid container"; docker inspect "$name" >/dev/null 2>&1 || deny "unknown container"; metadata "${argv[2]:-}" "${argv[3]:-}"; verb=${action#docker-}; if [[ $verb == stop ]]; then docker stop --time 30 "$name"; else docker "$verb" "$name"; fi; audit "$action" "$name" success "$INCIDENT" not-provided "$APPROVED" ;;
  docker-compose-up|docker-compose-down|docker-compose-restart|docker-compose-pull|docker-container-recreate)
    dir=$(compose_dir "$(decode_b64 "${argv[1]:-}")"); metadata "${argv[2]:-}" "${argv[3]:-}"; case "$action" in docker-compose-up) docker compose --project-directory "$dir" up -d;; docker-compose-down) docker compose --project-directory "$dir" down;; docker-compose-restart) docker compose --project-directory "$dir" restart;; docker-compose-pull) docker compose --project-directory "$dir" pull;; docker-container-recreate) svc=${argv[4]:-}; valid_name "$svc" || deny "invalid compose service"; docker compose --project-directory "$dir" up -d --force-recreate "$svc";; esac; audit "$action" "$dir" success "$INCIDENT" not-provided "$APPROVED" ;;
  vm-start|vm-shutdown|vm-reboot)
    name=$(vm_name "$(decode_b64 "${argv[1]:-}")"); metadata "${argv[2]:-}" "${argv[3]:-}"; case "$action" in vm-start) virsh start "$name";; vm-shutdown) virsh shutdown "$name";; vm-reboot) virsh reboot "$name";; esac; audit "$action" "$name" success "$INCIDENT" not-provided "$APPROVED" ;;
  vm-force-stop-plan)
    name=$(vm_name "$(decode_b64 "${argv[1]:-}")"); metadata "${argv[2]:-}" "${argv[3]:-}"; find "$PENDING" -type f -mmin +10 -exec mv -t "$USED" {} + 2>/dev/null || true; find "$PENDING" -type f -mmin -10 -print -quit | grep -q . && deny "another approval plan is pending"; token=$(openssl rand -hex 16); dest=$PENDING/$token.json; jq -cn --arg incident "$INCIDENT" --arg approved "$APPROVED" --arg name "$name" '{version:1,incident_id:$incident,diagnosis:"VM did not respond to graceful shutdown",target:$name,approval_timestamp:$approved,dangerous:true,argv:["/usr/bin/virsh","destroy",$name]}' > "$dest"; chmod 600 "$dest"; jq -cn --arg token "$token" --arg expires "$(date -u -d "+$TTL seconds" +%FT%TZ)" '{status:"PENDING",token:$token,expires:$expires,dangerous:true,confirmation:"CONFIRM-DANGEROUS-"+$token}' ;;
  vm-snapshot-create)
    name=$(vm_name "$(decode_b64 "${argv[1]:-}")"); snap=${argv[2]:-}; valid_name "$snap" || deny "invalid snapshot name"; metadata "${argv[3]:-}" "${argv[4]:-}"; virsh snapshot-create-as "$name" "$snap" --atomic; audit "$action" "$name:$snap" success "$INCIDENT" not-provided "$APPROVED" ;;
  service-start|service-stop|service-restart|service-reload)
    svc=${argv[1]:-}; script=$(service_script "$svc"); metadata "${argv[2]:-}" "${argv[3]:-}"; verb=${action#service-}; timeout 120 /bin/bash "$script" "$verb"; audit "$action" "$svc" success "$INCIDENT" not-provided "$APPROVED" ;;
  file-backup)
    target=$(normal_path "$(decode_b64 "${argv[1]:-}")"); metadata "${argv[2]:-}" "${argv[3]:-}"; backup=$(backup_file "$target"); audit "$action" "$target" "success:$backup" "$INCIDENT" not-provided "$APPROVED"; printf 'BACKUP=%s\n' "$backup" ;;
  file-copy|file-move)
    src=$(normal_path "$(decode_b64 "${argv[1]:-}")"); dst=$(normal_path "$(decode_b64 "${argv[2]:-}")"); metadata "${argv[3]:-}" "${argv[4]:-}"; [[ -f $src && ! -L $src ]] || deny "invalid source"; [[ ! -e $dst || -f $dst ]] || deny "invalid destination"; backup=none; [[ ! -e $dst ]] || backup=$(backup_file "$dst"); if [[ $action == file-copy ]]; then cp -a -- "$src" "$dst"; else mv -- "$src" "$dst"; fi; audit "$action" "$src->$dst" "success:backup=$backup" "$INCIDENT" not-provided "$APPROVED" ;;
  file-replace|file-edit)
    target=$(normal_path "$(decode_b64 "${argv[1]:-}")"); staged=${argv[2]:-}; hash=${argv[3]:-}; validator=${argv[4]:-auto}; metadata "${argv[5]:-}" "${argv[6]:-}"; [[ $staged =~ ^[A-Za-z0-9_.-]{1,128}$ && $hash =~ ^[a-f0-9]{64}$ ]] || deny "invalid staged artifact"; source=$STAGING/$staged; [[ -f $source && ! -L $source ]] || deny "staged artifact missing"; [[ $(sha256sum "$source" | awk '{print $1}') == "$hash" ]] || deny "staged hash mismatch"; validate_config "$source" "$validator" || deny "staged config validation failed"; backup=none; [[ ! -e $target ]] || backup=$(backup_file "$target"); install -m "$(stat -c %a "$target" 2>/dev/null || echo 600)" "$source" "$target"; validate_config "$target" "$validator" || { [[ $backup == none ]] || cp -a "$backup" "$target"; audit "$action" "$target" validation-failed "$INCIDENT" not-provided "$APPROVED" failed yes; deny "post-write validation failed; rollback performed"; }; rm -f "$source"; audit "$action" "$target" "success:backup=$backup" "$INCIDENT" not-provided "$APPROVED" passed no ;;
  config-validate) target=$(normal_path "$(decode_b64 "${argv[1]:-}")"); validate_config "$target" "${argv[2]:-auto}"; echo VALID ;;
  validation-record)
    metadata "${argv[1]:-}" "${argv[3]:-}"; result=$(decode_b64 "${argv[2]:-}"); [[ -n $result && ${#result} -le 1000 && $result != *$'\n'* ]] || deny "invalid validation result"; audit "$action" "$INCIDENT" recorded "$INCIDENT" not-provided "$APPROVED" "$result" no ;;
  mount|unmount)
    target=$(decode_b64 "${argv[1]:-}"); [[ $target =~ ^/mnt/(vm_storage|disks/[A-Za-z0-9_.-]+|remotes/[A-Za-z0-9_.-]+)$ ]] || deny "mount target not allowlisted"; metadata "${argv[2]:-}" "${argv[3]:-}"; if [[ $action == mount ]]; then mount "$target"; else umount "$target"; fi; audit "$action" "$target" success "$INCIDENT" not-provided "$APPROVED" ;;
  plan-register|dangerous-plan-register)
    find "$PENDING" -type f -mmin +10 -exec mv -t "$USED" {} + 2>/dev/null || true; find "$PENDING" -type f -mmin -10 -print -quit | grep -q . && deny "another approval plan is pending"; file=${argv[1]:-}; hash=${argv[2]:-}; [[ $file =~ ^[A-Za-z0-9_.-]{1,128}\.json$ && $hash =~ ^[a-f0-9]{64}$ ]] || deny "invalid plan reference"; src=$STAGING/$file; [[ -f $src && ! -L $src && $(sha256sum "$src" | awk '{print $1}') == "$hash" ]] || deny "plan hash mismatch"; jq -e '.version==1 and (.incident_id|type=="string" and length<=128) and (.diagnosis|type=="string" and length<=1000) and (.target|type=="string" and length<=500) and (.approval_timestamp|type=="string") and (.argv|type=="array") and (.argv|length>=1 and length<=32) and all(.argv[]; type=="string" and length<=4096 and ((contains("\n") or contains("\r"))|not))' "$src" >/dev/null || deny "invalid plan schema"; dangerous=$(jq -r '.dangerous // false' "$src"); [[ $dangerous == false || $dangerous == true ]] || deny "invalid dangerous flag"; [[ $action == dangerous-plan-register && $dangerous == true || $action == plan-register && $dangerous == false ]] || deny "wrong approval category"; token=$(openssl rand -hex 16); dest=$PENDING/$token.json; cp -- "$src" "$dest"; chmod 600 "$dest"; rm -f "$src"; jq -cn --arg token "$token" --arg expires "$(date -u -d "+$TTL seconds" +%FT%TZ)" --argjson dangerous "$dangerous" '{status:"PENDING",token:$token,expires:$expires,dangerous:$dangerous,confirmation:(if $dangerous then "CONFIRM-DANGEROUS-"+$token else null end)}' ;;
  plan-execute|dangerous-plan-execute)
    token=${argv[1]:-}; [[ $token =~ ^[a-f0-9]{32}$ ]] || deny "invalid plan token"; plan=$PENDING/$token.json; [[ -f $plan ]] || deny "unknown or already-used plan"; age=$(( $(date +%s) - $(stat -c %Y "$plan") )); (( age >= 0 && age <= TTL )) || { mv "$plan" "$USED/$token.expired"; deny "plan expired"; }; dangerous=$(jq -r '.dangerous // false' "$plan"); if [[ $dangerous == true ]]; then [[ $action == dangerous-plan-execute && ${argv[2]:-} == CONFIRM-DANGEROUS-$token ]] || deny "DANGEROUS ACTION requires exact second confirmation"; else [[ $action == plan-execute ]] || deny "wrong execution category"; fi; mapfile -t cmd < <(jq -r '.argv[]' "$plan"); exe=${cmd[0]}; if [[ $dangerous == false ]]; then case "$exe" in /usr/bin/touch) ((${#cmd[@]}==2)) || deny "touch requires exactly one target"; normal_path "${cmd[1]}" >/dev/null;; /bin/mkdir) if ((${#cmd[@]}==2)); then normal_path "${cmd[1]}" >/dev/null; elif ((${#cmd[@]}==3)) && [[ ${cmd[1]} == -p ]]; then normal_path "${cmd[2]}" >/dev/null; else deny "mkdir arguments not allowed"; fi;; /bin/cp|/bin/mv) ((${#cmd[@]}==3)) || deny "copy/move requires exact source and target"; normal_path "${cmd[1]}" >/dev/null; normal_path "${cmd[2]}" >/dev/null;; *) deny "generic command requires dangerous approval or a specific wrapper";; esac; else case "$exe" in /usr/bin/docker|/usr/bin/virsh|/sbin/mount|/sbin/umount|/usr/sbin/smartctl|/usr/sbin/nvme|/sbin/xfs_repair|/sbin/btrfs|/sbin/mkfs|/sbin/mkfs.xfs|/sbin/mkfs.btrfs|/bin/cp|/bin/mv|/usr/bin/install|/bin/mkdir|/usr/bin/touch|/bin/rm|/bin/chmod|/bin/chown|/sbin/reboot|/sbin/poweroff) ;; *) deny "dangerous executable not allowlisted";; esac; fi; incident=$(jq -r '.incident_id' "$plan"); diagnosis=$(jq -r '.diagnosis' "$plan" | head -c 500); target=$(jq -r '.target' "$plan" | head -c 300); approved=$(jq -r '.approval_timestamp // "not-provided"' "$plan"); mv "$plan" "$USED/$token.running"; set +e; timeout 900 "${cmd[@]}"; rc=$?; set -e; mv "$USED/$token.running" "$USED/$token.rc-$rc"; audit "$action" "$target" "exit=$rc" "$incident" "$diagnosis" "$approved" pending no; exit "$rc" ;;
  *) echo "DENIED: operator action not allowlisted" >&2; exit 126 ;;
esac
